# Number of Interactions
INTER_TIME: 5
# List of Random Seeds
SEED_LIST: [5, 10, 15, 20, 25]
INLR: 1e-3
# Interactive Adaptation Gradient Steps
INGS: 30
# Path for data
DATA_ROOT_DIR: 'D:/ICA_data/data'
# Path for log
LOG_DIR: './log'
# Path for checkpoints
CP_DIR: 'D:/ICA_data\checkpoints'