# Number of Interactions
INTER_TIME: 5
# List of Random Seeds
SEED_LIST: [5, 10, 15, 20, 25]
# Test Time Adaptation Learning Rate(Original Paper)
ADLR: 1e-7
# Test Time Adaptation Gradient Steps(Original Paper)
ADGS: 100
# Interactive Adaptation Learning Rate
INLR: 2e-2
# Interactive Adaptation Gradient Steps
INGS: 10
# Path for data
DATA_ROOT_DIR: '/data/add_disk1/yifeng/ICA_data/'
# Path for log
LOG_DIR: './ICA_log'
# Path for checkpoints
CP_DIR: '/data/add_disk1/yifeng/ICA_checkpoints/'